version: "3"

services:

  todofront:
    build: ./todo-app/front-end/
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback

  todoback:
    build: ./todo-app/back-end/
    restart: on-failure
    ports:
      - 3001:3001

  todotests:
    build: ./todo-app/tests/
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todofront
      - todoback
